-- MySQL Script generated by MySQL Workbench
-- 08/22/16 16:46:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema centro_multimedia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema centro_multimedia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `centro_multimedia` DEFAULT CHARACTER SET utf8 ;
USE `centro_multimedia` ;

-- -----------------------------------------------------
-- Table `centro_multimedia`.`generos_pelis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_multimedia`.`generos_pelis` (
  `idgeneros_pelis` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idgeneros_pelis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_multimedia`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_multimedia`.`peliculas` (
  `idpeliculas` INT NOT NULL AUTO_INCREMENT,
  `idgeneros_pelis` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `portada` VARCHAR(200) NOT NULL,
  `sinopsis` VARCHAR(400) NOT NULL,
  `formato` VARCHAR(100) NOT NULL,
  `duracion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idpeliculas`),
  INDEX `fk_generos_pelis_idx` (`idgeneros_pelis` ASC),
  CONSTRAINT `fk_generos_pelis`
    FOREIGN KEY (`idgeneros_pelis`)
    REFERENCES `centro_multimedia`.`generos_pelis` (`idgeneros_pelis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_multimedia`.`generos_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_multimedia`.`generos_series` (
  `idgeneros_series` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idgeneros_series`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_multimedia`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_multimedia`.`series` (
  `idseries` INT NOT NULL AUTO_INCREMENT,
  `idgeneros_series` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `portada` VARCHAR(200) NOT NULL,
  `temporadas_series` VARCHAR(20) NOT NULL,
  `sinopsis` VARCHAR(400) NOT NULL,
  `formato` VARCHAR(100) NOT NULL,
  `duracion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idseries`),
  INDEX `fk_generos_series_idx` (`idgeneros_series` ASC),
  CONSTRAINT `fk_generos_series`
    FOREIGN KEY (`idgeneros_series`)
    REFERENCES `centro_multimedia`.`generos_series` (`idgeneros_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_multimedia`.`genero_musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_multimedia`.`genero_musica` (
  `idgenero_musica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idgenero_musica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_multimedia`.`cantante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_multimedia`.`cantante` (
  `idcantante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `edad` DECIMAL(0,0) NOT NULL,
  `foto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcantante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_multimedia`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_multimedia`.`album` (
  `idalbum` INT NOT NULL AUTO_INCREMENT,
  `idcantante` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `caractura` VARCHAR(100) NOT NULL,
  `publicacion` DATE NOT NULL,
  `discografia` VARCHAR(100) NOT NULL,
  `calificacion` INT NOT NULL,
  PRIMARY KEY (`idalbum`),
  INDEX `fk_cantante_idx` (`idcantante` ASC),
  CONSTRAINT `fk_cantante`
    FOREIGN KEY (`idcantante`)
    REFERENCES `centro_multimedia`.`cantante` (`idcantante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_multimedia`.`musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_multimedia`.`musica` (
  `idmusica` INT NOT NULL AUTO_INCREMENT,
  `idgeneros` INT NOT NULL,
  `idcantante` INT NOT NULL,
  `idalbum` INT NOT NULL,
  `cancion` VARCHAR(100) NOT NULL,
  `caractura` VARCHAR(100) NOT NULL,
  `formato` VARCHAR(50) NOT NULL,
  `duracion` VARCHAR(50) NOT NULL,
  `reproduciones` INT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  PRIMARY KEY (`idmusica`),
  INDEX `fk_genero_musica_idx` (`idgeneros` ASC),
  INDEX `fk_cantante_idx` (`idcantante` ASC),
  INDEX `fk_album_idx` (`idalbum` ASC),
  CONSTRAINT `fk_genero_musica`
    FOREIGN KEY (`idgeneros`)
    REFERENCES `centro_multimedia`.`genero_musica` (`idgenero_musica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cantante`
    FOREIGN KEY (`idcantante`)
    REFERENCES `centro_multimedia`.`cantante` (`idcantante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album`
    FOREIGN KEY (`idalbum`)
    REFERENCES `centro_multimedia`.`album` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
